@startuml
autonumber
title Market Data

group Provider Setup
Provider -> Provider : Create subscriber T&Cs
note right: [T&C1] These are the provider's T&C's that they will require subscribers to sign
Provider -> Provider : Create data sets
end

group Redistributor Setup
Redistributor -> Provider : Download dataset
Redistributor -> Redistributor : Create subscriber T&Cs
note right: T&C2
Redistributor -> Redistributor : Create distributable data set
end

group Subscriber Permission
Subscriber -> Redistributor : Download distributable data sets
activate Redistributor
Redistributor --> Subscriber : Send distributable data sets
deactivate Redistributor
Subscriber -> Redistributor : Request specific data set
activate Redistributor
Redistributor --> Subscriber : Send data set and associated T&Cs
deactivate Redistributor
Subscriber -> Subscriber: Sign all T&Cs
note right: T&C1 and T&C2

Subscriber -> Redistributor : Request permission
activate Subscriber
note right: Include the signed T&Cs from [10]
Subscriber -> Provider
deactivate Subscriber
end

group Usage
Subscriber -> Redistributor : Create Usage
activate Subscriber
Subscriber -> Provider
deactivate Subscriber
note right: Usage is sent to all parties

Redistributor -> Subscriber : Issue receipt
activate Redistributor
Redistributor -> Provider
deactivate Redistributor
end

group Usage with Existing Token
Subscriber -> Redistributor2 ** : Create Usage
activate Subscriber
Subscriber -> Provider
deactivate Subscriber
note right: Usage receipt is sent to all parties, providing an existing usage token as proof of payment
end

@enduml